site_name: mkdocs-custom
site_author: humangas
site_description: mkdocsで、javascript ライブラリ サンプル
site_url: https://humangas.github.io/mkdocs-custom/
repo_url: https://github.com/humangas/mkdocs-custom/

theme: readthedocs

extra_javascript:
  # https://github.com/adrai/flowchart.js/blob/master/src/jquery-plugin.js
  - js/flowchartjs/jquery-plugin.js
extra_css: []

#markdown_extensions:
#      - fontawesome_markdown

pages:
  - 'Home': 'index.md'
  - 'vis': 'vis.md'
  - 'viz': 'viz.md'
  - 'flowchartjs': 'flowchartjs.md'
  - 'js-sequence-diagrams': 'js-sequence-diagrams.md'
  - 'chartjs': 'chartjs/index.md'
  - 'chartistjs': 'chartistjs/index.md'
  - 'mermaid': 'mermaid.md'

dev_addr: 0.0.0.0:8000
